package usyd.comp5216.dkthero.questions;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

import usyd.comp5216.dkthero.R;
import usyd.comp5216.dkthero.models.QuizModel;


public class GenerateQuestions {


    public List<QuizModel> listQuiz(String category) {
        List<QuizModel> list = new ArrayList<>();
        if (category.equals("ICAC and General 1")) {
            list.add(new QuizModel(category,	"What will happen if you are caught cheating on the knowledge test?", new String[]{	"You will never be allowed to take another test.",	"You will not be allowed to take another test for 6 weeks.",	"Nothing, there is no penalty."}, 1));
            list.add(new QuizModel(category,	"What will happen if you offer a testing officer a bribe to pass your driving test?", new String[]{	"Nothing, there is no penalty.",	"Only the testing officer will be investigated.",	"Action will be taken against you. The penalties are severe and include fines and imprisonment."}, 2));
            list.add(new QuizModel(category,    "What will happen if a testing officer asks you for a bribe to pass your driving test and you give it to him or her?", new String[]{	"Nothing, there is no penalty.",	"Action will be taken against all involved. The penalties are severe and include fines and imprisonment.",	"Only the testing officer will be investigated."}, 1));
            list.add(new QuizModel(category, 	"Where there is parallel kerbside parking, are you allowed to double", new String[]{	"Yes, if delivering goods.",	"No, not at any time.",	"Yes, if not obstructing traffic."}, 1));
            list.add(new QuizModel(category, 	"You are driving at night with your headlights on high beam. When should you dip your headlights?", new String[]{	"Never, you are allowed to drive with your lights on high beam at all times.",	"When within 200 metres of an oncoming vehicle only.",	"When within 200 metres of the vehicle ahead or an oncoming one."}, 2));
            list.add(new QuizModel(category, 	"If an oncoming vehicle crosses the centre line and is coming straight at you and you cannot stop, you should", new String[]{	"Drive onto the wrong side of the road and hope the other vehicle does not do the same.",	"Slow down and hope that the driver will turn away.",	"Brake, look for room to the left, sound your horn and flash your lights."}, 2));
            list.add(new QuizModel(category, 	"If you are involved in an accident where your vehicle needs to be towed away and the Police does not attend the crash scene, you", new String[]{	"Do not need to report the accident to the Police.",	"Must report the accident to the Police Station nearest to where the accident happened within 24 hours.",	"Only need to report the accident to the Police if someone was injured."}, 1));
            list.add(new QuizModel(category, 	"You should use your right-hand indicator when", new String[]{	"You intend to move to the right, at any time.",	"You are about to stop. ",	"You intend to slow down. "}, 0));
            list.add(new QuizModel(category, 	"When merging onto the freeway from the entrance, you should", new String[]{	"Sound your horn, turn on your indicator lights and move onto the freeway.",	"Look for a large enough break in the traffic and adjust your speed so as to fit into the traffic flow.",	"Stop and check the traffic behind you on the entrance."}, 1));
            list.add(new QuizModel(category, 	"If you see a sign indicating road repairs are going on, you should", new String[]{	"Stop immediately and wait for instructions.",	"Slow down and watch for traffic controllers and instructions.",	"Maintain the same speed."}, 1));
            list.add(new QuizModel(category, 	"You see a broken yellow line painted on the roadway adjacent to the kerb. What does it mean?", new String[]{	"Clearway restrictions apply - you must not stop during the clearway hours.",	"You may at any time, park along this part of the road for 1 hour only.",	"Bicycle riders must ride along the yellow line."}, 0));
            list.add(new QuizModel(category, 	"If you see a horse and rider on the road what should you do?", new String[]{	"Sound your horn to warn the rider.",	"Speed up to pass the horse.",	"Slow down and give them plenty of room."}, 2));
            list.add(new QuizModel(category, 	"Generally, if you hear the siren of an emergency vehicle you should", new String[]{	"Immediately come to a stop.",	"Pull over to the left until the emergency vehicle passes.",	"Let the emergency vehicle pass and follow it closely behind."}, 1));
            list.add(new QuizModel(category, 	"Bicycle and motorcycle riders have the same rights to use the road as other motor vehicle drivers. They are, however, more at risk in traffic because", new String[]{	"They ride too fast and do not turn their lights on.",	"They are careless and do not obey road rules.",	"They are harder to see in traffic and do not have the same protection as many drivers."}, 2));
            list.add(new QuizModel(category,	"If you are driving towards a road works zone and a traffic controller displays a stop sign you must", new String[]{	"Stop your vehicle and follow the directions of the traffic controller.",	"Stop and then proceed if you think it is safe.",	"Slow down and continue through the road works zone."}, 0));
            list.add(new QuizModel(category,	"Do bicycle riders have the same rights and responsibilities as drivers and motorcycle riders?", new String[]{	"Yes.",	"No, they must always ride on the footpath.",	"No, they must give way to cars at all times when riding on the road."}, 0));
            list.add(new QuizModel(category,	"When is a motorcycle rider allowed to ride without an approved helmet?", new String[]{	"Never.",	"When the rider has a medical certificate.",	"Only during daylight hours."}, 0));
            list.add(new QuizModel(category,	"What equipment must be fitted to a motorcycle if pillion passengers are to be carried?", new String[]{	"Separate footrests and a pillion seat.",	"Heavy duty shock absorbers.",	"An engine of more than 250ml capacity."}, 0));
            list.add(new QuizModel(category,	"You need to stop quickly, you should use", new String[]{	"The front brake only.",	"Both brakes together.",	"The rear brake only."}, 1));
            list.add(new QuizModel(category,	"To make a normal stop, you should use", new String[]{	"The rear brake only.",	"Both front and rear brakes.",	"The front brake only."}, 1));
            list.add(new QuizModel(category,	"You are going to make a turn. When should you apply the brakes?", new String[]{	"Before you start the turn.",	"As you come out of the turn.",	"While you are in the turn."}, 0));
            list.add(new QuizModel(category,	"If you have to downshift for a turn, you should do it", new String[]{	"Just as you begin the turn.",	"Before you start the turn.",	"While you are in the turn."}, 1));
            list.add(new QuizModel(category,	"If you wear regular spectacles while you ride", new String[]{	"You must not ride at night.",	"You need no other eye protection.",	"You should also wear a face shield or visor."}, 2));
            list.add(new QuizModel(category,	"Every time before you ride you should check", new String[]{	"Your fuel tap is not on ‘reserve’.",	"That the headlight and stop light are working.",	"The expiry date of your licence."}, 1));
            list.add(new QuizModel(category,	"What should you be able to see in each mirror fitted to your motorcycle?", new String[]{	"About half of the lane behind you and as much as possible of the lane next to you.",	"The lane behind.",	"Your shoulder and the lane behind."}, 0));

            list.add(new QuizModel(category, R.drawable.cg013,	"What is meant by this sign on or near a bridge?", new String[]{	"Stop at all times before crossing the bridge and only give way to pedestrians who may be crossing.",	"Slow down and be prepared to give way to vehicles travelling in the opposite direction.",	"Do not overtake a vehicle travelling in the same direction."}, 1));
            list.add(new QuizModel(category, R.drawable.cg031,	"You are driving in a 60 km/h zone, with only one lane for traffic in your direction. You see a bus ahead (with this sign displayed on the rear) signalling its intention to pull out from a bus stop, you should", new String[]{	"Continue at your normal speed as the bus does not have priority.",	"Sound your horn to stop the bus from pulling out.",	"Slow down, and give way to the bus as it has priority."}, 2));
            list.add(new QuizModel(category, R.drawable.cg045,	"If your vehicle is involved in an accident (regardless of the damage), what details must you give, to the other driver(s), if asked?", new String[]{	"You must let them see your licence, take details, and give the name and address of the vehicle's owner.",	"No details at all until you have contacted your insurance company.",	"Only your name and address details if a Policeman asks for them."}, 0));
            list.add(new QuizModel(category, R.drawable.cg046,	"If a vehicle you are driving is involved in an accident and a person is injured, what must you do after stopping?", new String[]{	"Render every assistance and take immediate steps to have an ambulance notified. Then call the Police.",	"Only call the Police if the accident also resulted in over $500 worth of property damage.",	"Report the accident to Police within seven days."}, 0));

        }
        if (category.equals("ICAC and General 2")) {
            list.add(new QuizModel(category, 	"When you slow down for a stop, you should", new String[]{	"Downshift only if there is traffic ahead of you.",	"Downshift before stopping.",	"Downshift after stopping."}, 1));
            list.add(new QuizModel(category, 	"On a wet road how do you make an emergency stop? ", new String[]{	"Apply the rear brake only.",	"Apply the front and rear brakes together.",	"Apply the front brake only if the rear wheel begins to slide."}, 1));
            list.add(new QuizModel(category, 	"Where should you look when following a car?", new String[]{	"hand side of the car you are following.",	"To the right",	"At the car's brake lights."}, 2));
            list.add(new QuizModel(category, 	"In what part of the lane should you ride when being passed by on", new String[]{	"No special part of your lane.",	"The centre or left of your lane.",	"As close to the centre line as possible."}, 1));
            list.add(new QuizModel(category, 	"A turn signal that keeps flashing after a turn is very likely to", new String[]{	"Damage the electrical system.",	"Confuse other drivers and cause them to turn into your path.",	"Keep other drivers from seeing your brake light."}, 1));
            list.add(new QuizModel(category, 	"You are being overtaken by a car on a two", new String[]{	"No special part of your lane.",	"The centre or left of your lane.",	"The far right of your lane."}, 1));
            list.add(new QuizModel(category, 	"If you have not ridden a particular motorcycle before, you should", new String[]{	"Allow extra stopping distance.",	"Use the rear brake only.",	"Not go faster than 30 km/h."}, 0));
            list.add(new QuizModel(category, 	"When riding on a wet road, what is usually the most slippery part?", new String[]{	"The right wheel track.",	"The centre of the lane.",	"The left wheel track."}, 1));
            list.add(new QuizModel(category, 	"You are riding along on a sealed road when you see sand on the road ahead. What should you do?", new String[]{	"Slow down because it takes longer to stop on a slippery road surface.",	"Stay at the same speed.",	"Increase your speed."}, 0));
            list.add(new QuizModel(category, 	"When riding over loose gravel or sand, you should", new String[]{	"Slow down by using the front brake only.",	"Change up to a higher gear.",	"Avoid sudden or quick movements."}, 2));
            list.add(new QuizModel(category, 	"When riding on a bumpy road", new String[]{	"Keep your normal seating position.",	"Rise slightly on the footrests so that you can absorb the shock with your knees and elbows.",	"Take your feet off the footpegs."}, 1));
            list.add(new QuizModel(category, 	"What is the first thing to do if you have a blowout?", new String[]{	"Brake lightly on the wheel with the good tyre.",	"Hold the hand grips tightly. Gradually close the throttle and let the motorcycle slow down.",	"Turn quickly off the road."}, 1));
            list.add(new QuizModel(category, 	"At low speeds, if the rear tyre goes flat what is the first thing you will notice?", new String[]{	"The steering will feel heavy.",	"The rear of the motorcycle will tend to slide from side to side.",	"Your brakes will not work."}, 1));
            list.add(new QuizModel(category, 	"To handle a high speed wobble, firmly grip the handlebars and", new String[]{	"Allow the motorcycle to slow down.",	"Increase your speed.",	"Quickly apply the brakes."}, 0));
            list.add(new QuizModel(category, 	"If your throttle sticks while in traffic, what is the first thing you should do?", new String[]{	"off switch and apply the brakes.",	"Rotate the throttle back and forth several times.",	"Sound your horn to warn other vehicles."}, 0));
            list.add(new QuizModel(category, 	"When carrying a pillion passenger, the passenger should sit", new String[]{	"Behind and as close as possible to the rider.",	"Behind and as far from the rider as possible.",	"In front of and as close to the rider as possible."}, 0));
            list.add(new QuizModel(category, 	"In a turn you should tell a pillion passenger to", new String[]{	"Lean in the same direction as the rider.",	"Stay upright.",	"Lean in the opposite direction from the turn."}, 0));
            list.add(new QuizModel(category, 	"What should a pillion passenger do when you stop?", new String[]{	"Place the same foot on the ground as the rider.",	"Place both feet on the ground.",	"Keep both feet on the footpegs."}, 2));
            list.add(new QuizModel(category, 	"A pillion passenger should hold on to", new String[]{	"The rider's waist, hips or passenger's handgrip.",	"The rider's arms.",	"The rider's helmet."}, 0));
            list.add(new QuizModel(category, 	"How old must you be to obtain a learner rider licence?", new String[]{	"16 years of age.",	"16 years and 9 months of age.",	"16 years and 3 months of age."}, 1));
            list.add(new QuizModel(category, 	"If you are stopped by Police while riding a motorcycle on a road or road related area and you are not carrying your rider's licence you could expect to be", new String[]{	"Given an on-the-spot fine or summonsed to Court by Police.",	"Given twelve hours to produce it at your local Police Station.",	"Told to go home and get it."}, 0));
            list.add(new QuizModel(category, 	"Police officers may check that you are correctly licensed when", new String[]{	"Riding on a freeway or motorway.",	"You stop to pay tolls.",	"You are stopped for Random Breath Testing."}, 2));
            list.add(new QuizModel(category, 	"Wearing the right protective clothing when riding can", new String[]{	"Greatly reduce injury in the event of a crash.",	"Make you very hot and reduce your ability to ride.",	"Make no difference to you when you ride."}, 0));
            list.add(new QuizModel(category, 	"When are you allowed to ride a motorcycle on roads in NSW without wearing a helmet?", new String[]{	"When the temperature reaches 32 degrees in summer.",	"When you have a doctor's certificate.",	"Never."}, 2));
            list.add(new QuizModel(category, 	"What should be displayed upon an approved helmet?", new String[]{	"A manufacturer's approval and checked by sticker.",	"Bright stickers to make the helmet more visible to vehicle drivers.",	"An Australian Standards AS1698 sticker."}, 2));
            list.add(new QuizModel(category, 	"To ensure a helmet is in good condition you should", new String[]{	"Only buy a helmet that someone else has tried out first.",	"Only purchase a new one. Never buy a second hand helmet.",	"Check to make sure it has not been dropped."}, 1));
            list.add(new QuizModel(category, 	"If you have a crash whilst wearing your helmet you should", new String[]{	"Check to make sure it is not damaged.",	"Replace it.",	"If it is scratched or chipped get it repainted."}, 1));
            list.add(new QuizModel(category, 	"If you find cracks or loose padding in your helmet you should", new String[]{	"Have it repaired by an authorised person.",	"Replace it.",	"Use high speed duct tape to hold it together as it is waterproof."}, 1));
            list.add(new QuizModel(category, 	"Wearing a helmet visor or goggles when riding will", new String[]{	"Reduce your vision and should only be worn in the rain.",	"Protect your eyes from the wind, dust, rain, insects or stones thrown up by other vehicles.",	"Not make much difference to your riding on a fine day when there is no wind."}, 1));
            list.add(new QuizModel(category, 	"The best type of footwear when riding are", new String[]{	"Trainers or Joggers.",	"Boots which provide ankle protection.",	"Steel toe capped boots."}, 1));
            list.add(new QuizModel(category, 	"Protective clothing should be", new String[]{	"Very tight so they won't move if you fall off your bike.",	"Comfortable without being loose.",	"Loose to allow air flow to keep you cool in summer."}, 1));
            list.add(new QuizModel(category, 	"Other protective options to wear when riding include", new String[]{	"Light cotton shirt and pants.",	"Nylon jacket and pants.",	"Back protectors to protect your spine and kidney belts."}, 2));
            list.add(new QuizModel(category, 	"When learning to ride you should", new String[]{	"Start in quiet streets that you know well.",	"Ride in groups so that you are protected from cars.",	"Gain experience in complex traffic situations to build your skills quickly."}, 0));
            list.add(new QuizModel(category, 	"Any passenger carried on a motorcycle (not in a sidecar) must", new String[]{	"Be eight years of age or older.",	"Be at least six years of age.",	"Be a holder of a rider licence."}, 0));
            list.add(new QuizModel(category, 	"Your ability to concentrate can be affected by", new String[]{	"Fatigue, alcohol, drugs and the clothing you wear.",	"The type of motorcycle you ride.",	"Whether you are familiar with the road you are riding on."}, 0));
            list.add(new QuizModel(category, 	"Correct riding posture", new String[]{	"Will make you more visible to other road users.",	"Is whatever position you are most comfortable in.",	"Reduces fatigue and improves control."}, 2));

            list.add(new QuizModel(category, R.drawable.cg090,	"You hear the siren of an ambulance approaching you from behind. You should", new String[]{	"Slow down to the speed of other traffic.",	"Move into the left lane.",	"Continue at the same speed."}, 1));
            list.add(new QuizModel(category, R.drawable.cg102,	"You want to park your vehicle for a short time. It is night time. You should", new String[]{	"Leave your headlights on high beam.",	"Park on the footpath.",	"Pick a visible position or leave the parking or hazard lights on."}, 2));
            list.add(new QuizModel(category, R.drawable.cg113,	"Looking at the diagrams, how far from the approach side of a bus stop or a railway crossing are you allowed to stand or park your vehicle?", new String[]{	"At least 20 metres.",	"At least 50 metres.",	"At least 5 metres."}, 0));
            list.add(new QuizModel(category, R.drawable.cg119,	"If you are driving through a road work zone in the left hand lane and you see this sign you should", new String[]{	"Stop and wait for directions.",	"Speed up to get in front of any cars traveling in the right hand lane.",	"Merge to the right and give way to other traffic."}, 2));

        }
        if (category.equals("Fatigue and Defensive")) {
            list.add(new QuizModel(category, 	"Under good conditions, when driving behind any vehicle, at any speed, you should", new String[]{	"Stay at least three seconds behind the vehicle in front of you.",	"Drive as close to the vehicle in front as possible.",	"Stay one second behind the vehicle in front of you."}, 0));
            list.add(new QuizModel(category, 	"When driving in wet weather, your vehicle will", new String[]{	"Stop in the same distance as on a dry road.",	"Take longer and further to stop, so slow down.",	"Handle better, so you can go faster."}, 1));
            list.add(new QuizModel(category, 	"At night, if an oncoming vehicle's headlights dazzle you, you should", new String[]{	"Close your eyes for a short time until they recover.",	"Watch the centre line of the road.",	"Slow down, until your eyes recover."}, 2));
            list.add(new QuizModel(category, 	"If you get sleepy while driving, it is best to", new String[]{	"Stop, rest, and change drivers if possible.",	"Turn on the radio very loud.",	"Turn on the air conditioning or open the windows."}, 0));
            list.add(new QuizModel(category, 	"In wet weather when it becomes hard for you to see, you should", new String[]{	"Flash your headlights to warn other drivers.",	"Turn your headlights on high beam.",	"Turn on your headlights, slow down, and double your following distance behind the vehicle in front."}, 2));
            list.add(new QuizModel(category, 	"If you are driving and it starts to rain, you should", new String[]{	"Put your lights on high beam so you can see better.",	"Slow down using the brake gently, since rain and oil may create a slippery surface.",	"Put your hazard warning lights on and increase your speed to avoid the rain."}, 1));
            list.add(new QuizModel(category, 	"When driving on a slippery wet road, for example, one covered in early morning dew, your vehicle will ", new String[]{	"Be heavier to steer.",	"Take longer and further to stop.",	"Be easier to steer and handle."}, 2));
            list.add(new QuizModel(category, 	"Why should you avoid heavy braking on a wet road?", new String[]{	"You might wet pedestrians walking along the footpath.",	"If the wheels lock up your handbrake may not work.",	"Your wheels may skid and cause a loss of control."}, 2));
            list.add(new QuizModel(category, 	"At night you should", new String[]{	"Drive closer to the vehicle in front so they can see you better.",	"Use your hazard warning lights when overtaking another vehicle.",	"Leave a longer gap behind the vehicle in front."}, 2));
            list.add(new QuizModel(category, 	"When going on a long trip, out of the following which is the most important to do?", new String[]{	"Make sure your horn is working.",	"Get plenty of rest before starting out.",	"Have a good meal before driving."}, 1));
            list.add(new QuizModel(category, 	"At night, when you approach an oncoming vehicle, you should", new String[]{	"Carefully watch the vehicle by looking directly at its headlights.",	"Not look at its headlights, but keep left and watch the left of the road.",	"Put your lights on high beam, to make your vehicle more easily seen."}, 1));
            list.add(new QuizModel(category, 	"To help prevent fatigue when riding you should", new String[]{	"Dress to protect yourself fully from wind, heat, cold and rain and not ride any longer than two hours at a time.",	"Stop and rest at least every four hours.",	"Ride in short sleeves shirt with no gloves to allow the wind to keep you awake."}, 0));
            list.add(new QuizModel(category, 	"What should you do if you have difficulty concentrating when riding? ", new String[]{	"Constantly change your speed up and down to help you concentrate on what you are doing.",	"Ride without gloves and in a short sleeves shirt to allow the wind on your body to help you concentrate.",	"Stop immediately and rest."}, 2));

        }
        if (category.equals("Intersections 1")) {
            list.add(new QuizModel(category, 	"As you approach an intersection, you should check for traffic on your left and right", new String[]{	"At all times before entering the intersection.",	"Only when the traffic is heavy.",	"Only when you approach a stop sign."}, 0));
            list.add(new QuizModel(category, 	"If a STOP or GIVE WAY sign has been knocked down, for example, as the result of an accident, does the line marked across the road have any meaning?", new String[]{	"No, but you must give way if turning.",	"Yes, it has the same meaning as the sign itself.",	"No, you only need to give way to the vehicle on your right."}, 1));
            list.add(new QuizModel(category, 	"Right-turns must be made from which lanes when travelling on a laned roadway?", new String[]{	"The lane carrying the least amount of traffic.",	"The far right-hand lane or any other lane having an arrow pointing right.",	"The far left-hand lane."}, 1));
            list.add(new QuizModel(category, 	"You want to make a left turn. You must use your left-hand indicator", new String[]{	"Only when there is traffic behind you.",	"Only when arrows are marked on the roadway.",	"At all times."}, 2));
            list.add(new QuizModel(category, 	"You wish to make a right-hand turn from a ONE WAY STREET with no arrows marked on the roadway. You should position your vehicle", new String[]{	"On the left-hand side of the street.",	"In the middle of the street.",	"On the right-hand side of the street."}, 2));
            list.add(new QuizModel(category, 	"When there are no arrows marked on the road, left turns must be made from", new String[]{	"The far left-hand side of the road.",	"The middle of the road. ",	"Either side of the road."}, 0));
            list.add(new QuizModel(category, 	"If the boomgates are down and the signals are flashing, at a railway level crossing, you may begin to cross", new String[]{	"Only when the gate is up and the lights stop flashing.",	"If you cannot see a train approaching.",	"If you can safely go around the closed gate."}, 0));
            list.add(new QuizModel(category, 	"Which statement is correct?", new String[]{	"Red light cameras take photographs of vehicles that enter intersections when the lights are red.",	"Red light cameras take photographs of vehicles that speed through intersections.",	"Red light cameras take photographs of vehicles that cross intersections when the lights are yellow."}, 0));
            list.add(new QuizModel(category, 	"When police officers are at intersections giving directions you must", new String[]{	"Always follow any instruction they give you.",	"Drive through the intersection as you normally would.",	"Wait for the traffic lights to start working again."}, 0));
            list.add(new QuizModel(category, 	"If you enter an intersection that is under the control of a traffic controller", new String[]{	"Stop at the intersection and then proceed slowly.",	"Sound your horn at the traffic controller and hope they get out of your way.",	"Follow the directions of the controller."}, 2));
            list.add(new QuizModel(category, 	"You are at an intersection and see a pedestrian crossing the road into which you are turning. You must", new String[]{	"Sound your horn to warn the pedestrian to get out of the way.",	"Give way to the pedestrian.",	"Swerve around the pedestrian to avoid hitting them."}, 1));

            list.add(new QuizModel(category, R.drawable.in003,	"When making a righthand turn at the intersection shown, you must give way to", new String[]{	"An oncoming vehicle going straight ahead or turning left and any vehicle on your right.",	"A vehicle approaching from your left and intending to turn right.",	"Only pedestrians."}, 0));
            list.add(new QuizModel(category, R.drawable.in004,	"If turning right at a T~intersection (as shown) must you give way to vehicles approaching from both the left and right?", new String[]{	"Yes, whether they are turning or not.",	"No, only the vehicle on the right.",	"No, you have right of way."}, 0));
            list.add(new QuizModel(category, R.drawable.in006,	"If turning at an intersection are you required to give way to pedestrians?", new String[]{	"Yes, a driver turning right or left must give way to pedestrians, if there is a danger of a collisio.",	"Yes, only if turning left.",	"Yes, only if turning right."}, 0));
            list.add(new QuizModel(category, R.drawable.in007,	"When you come to an intersection and the road beyond is choked with vehicles going in the same direction, what should you do?", new String[]{	"Wait until there is room for you to completely cross the intersection.",	"Proceed if there is no traffic on your right.",	"Travel into the intersection and wait until traffic ahead moves."}, 0));
            list.add(new QuizModel(category, R.drawable.in010,	"in this diagram both vehicles O and P must pass through GIVE WAY signs before entering the intersection. Which vehicle goes first?", new String[]{	"Vehicle P.",	"Vehicle O.",	"It depends on who moves first."}, 0));
            list.add(new QuizModel(category, R.drawable.in011,	"Vehicle O is at a STOP sign", new String[]{	"Vehicle O must give way only to vehicle R.",	"Vehicle O must give way to vehicles P, Q and R.",	"All vehicles must give way to vehicle O."}, 1));
            list.add(new QuizModel(category, R.drawable.in012,	"If both vehicles P and O in the diagram are turning right, which vehicle is in the best position to turn left into the street marked 'X'?", new String[]{	"Vehicle O.",	"Vehicle P.",	"Neither vehicle."}, 0));
            list.add(new QuizModel(category, R.drawable.in013,	"The diagram shows a marked pedestrian crossing at an intersection. There is also a STOP sign at the intersection. You have already stopped for a pedestrian. Must you stop again at the STOP line?", new String[]{	"No, if the intersection is clear.",	"Yes, if there is traffic on your right only.",	"Yes, at all times."}, 2));
            list.add(new QuizModel(category, R.drawable.in014,	"A GIVE WAY sign at an intersection means that you must", new String[]{	"Be ready to stop and give way to all other traffic if there is danger of a collision.",	"Stop completely at all times and have no right of way.",	"Slow down and only give way to traffic on your right."}, 0));
            list.add(new QuizModel(category, R.drawable.in016,	"Which vehicle in the diagram must give way?", new String[]{	"Vehicle J.",	"Vehicle K.",	"Vehicle L."}, 0));
            list.add(new QuizModel(category, R.drawable.in019,	"At the T-intersection shown in the diagram which vehicle should give way?", new String[]{	"Vehicle R.",	"Vehicle Q.",	"Whichever vehicle got there last."}, 0));

        }
        if (category.equals("Intersections 2")) {

            list.add(new QuizModel(category, R.drawable.in026,	"What should you do on approaching a railway level crossing displaying a STOP sign?", new String[]{	"Stop at all times and proceed when safe to do so.",	"Slow down to 10 km/h, then proceed through the crossing.",	"Stop, only if a train is at the crossing."}, 0));
            list.add(new QuizModel(category, R.drawable.in027,	"You are driving the car in the diagram. You must stop", new String[]{	"Only if there is danger of a collision with another vehicle.",	"Only if there is a car on your right or left.",	"Even when there is no other traffic."}, 2));
            list.add(new QuizModel(category, R.drawable.in029,	"When approaching a railway level crossing displaying this sign, you must", new String[]{	"Slow down, look both ways for trains and be prepared to stop if necessary.",	"increase your speed to avoid any approaching trains.",	"Continue across at normal speed, do not slow down."}, 0));
            list.add(new QuizModel(category, R.drawable.in030,	"Even if the signal at a railway level crossing does not indicate that a train is coming, you should", new String[]{	"Speed up and cross the tracks quickly.",	"Slow down, be ready to stop and give way if there is danger of collision.",	"Stop completely at all times."}, 1));
            list.add(new QuizModel(category, R.drawable.in035,	"You approach an intersection in busy traffic and want to go straight ahead. The traffic lights turn green. When are you permitted to enter the intersection?", new String[]{	"Only when there is room for your vehicle on the other side.",	"Immediately after the traffic lights turn green.",	"When the vehicle behind signals you to go."}, 0));
            list.add(new QuizModel(category, R.drawable.in040,	"As you drive into an intersection, the lights turn to yellow. You should", new String[]{	"Accelerate as hard as you can.",	"Continue through the intersection.",	"Brake immediately to a stop."}, 1));
            list.add(new QuizModel(category, R.drawable.in044,	"You drive up to an intersection with a stop sign. There is no painted stop line. Where should you stop?", new String[]{	"At least five metres before the intersection.",	"Before coming to and as near to the intersection as possible.",	"At the point where you can see clearly in both directions."}, 1));
            list.add(new QuizModel(category, R.drawable.in056,	"You wish to turn left at this roundabout. Which lane may you use?", new String[]{	"Right lane.",	"Left lane.",	"Either lane."}, 1));
            list.add(new QuizModel(category, R.drawable.in057,	"You are in the right hand lane and are planning to go straight ahead through this roundabout. When should you signal left to exit the roundabout?", new String[]{	"After point O.",	"After point N.",	"After point M."}, 0));
            list.add(new QuizModel(category, R.drawable.in058,	"When you wish to turn left at a roundabout you indicate", new String[]{	"Left only after you enter the roundabout.",	"Only if you think it necessary.",	"Left from start to finish."}, 2));
            list.add(new QuizModel(category, R.drawable.in059,	"You wish to go straight ahead at this roundabout. Which statement is true?", new String[]{	"You must always leave the roundabout in the left lane.",	"You must enter in the right lane and leave in the left.",	"You must leave the roundabout in the same lane as you entered."}, 2));

            list.add(new QuizModel(category, R.drawable.in060,	"You want to turn left at this roundabout. Which lane must you use?", new String[]{	"Lane B.",	"Lane A.",	"Either lane."}, 1));
            list.add(new QuizModel(category, R.drawable.in061,	"When you wish to drive straight ahead at a roundabout you may enter from either the left or right lane. As you continue around you should", new String[]{	"Move into another lane with least traffic.",	"Keep in the lane you entered the roundabout.",	"Change lanes to get through quickly."}, 1));
            list.add(new QuizModel(category, R.drawable.in062,	"When turning left at a roundabout you should enter and leave the roundabout", new String[]{	"in the lane with least traffic.",	"in the right lane.",	"in the left lane."}, 2));
            list.add(new QuizModel(category, R.drawable.in063,	"You wish to go straight ahead on this roundabout with two lanes. Which lane may you use?", new String[]{	"Left lane only.",	"Either lane.",	"Right lane only."}, 1));
            list.add(new QuizModel(category, R.drawable.in064,	"The motorcyclist wants to travel straight ahead through this roundabout. The rider should watch out for the marked car because the car", new String[]{	"May stop suddenly.",	"Could be going too fast.",	"May be leaving the roundabout."}, 2));
            list.add(new QuizModel(category, R.drawable.in065,	"To turn back into the same road from which you joined this roundabout you must", new String[]{	"Stay in the right lane all the way round.",	"Move into the left lane to leave the roundabout.",	"Use the left lane all the way round."}, 0));
            list.add(new QuizModel(category, R.drawable.in067,	"The red car wants to turn right and exit the roundabout in the street indicated by an arrow. Is the car positioned in the correct lane to do this?", new String[]{	"Yes, the car can make the turn only from this lane.",	"No, the car should enter the roundabout only from the right hand lane.",	"Yes, the car can make the turn from either the left hand or the right hand lane."}, 1));

        }
        if (category.equals("Negligent Driving")) {
            list.add(new QuizModel(category, 	"When driving near parked vehicles, you should", new String[]{	"Stop, if you see a car with its right-hand indicator on.",	"Check for parked vehicles with turn signals on, or children about to step out.",	"Sound your horn and flash your headlights to warn drivers not to pull out."}, 1));
            list.add(new QuizModel(category, 	"You are approaching a hill or curve. You must not cross the centre line to overtake", new String[]{	"If you cannot see clear road ahead for 75 metres.",	"If you cannot see clear road ahead for 100 metres.",	"If you do not have a clear view of any approaching traffic."}, 2));
            list.add(new QuizModel(category, 	"You are approaching the crest (top of a hill) on a narrow road, the safest procedure is to", new String[]{	"Increase your speed and sound your horn.",	"Flash your headlights to warn oncoming traffic.",	"Keep to the left and slow down."}, 2));
            list.add(new QuizModel(category, 	"When overtaking another vehicle you should NOT move back in front of it, unless –", new String[]{	"The driver of the vehicle signals it is safe to do so.",	"An oncoming car appears over a hill.",	"You can see the overtaken vehicle in your rear vision mirror."}, 2));
            list.add(new QuizModel(category, 	"A driver behind you signals their intention to overtake your car. What should you do? ", new String[]{	"Keep to the left and let that driver overtake you.",	"Speed up so that the driver will not have to overtake.",	"Signal the driver to remain behind you if it is travelling too fast."}, 0));
            list.add(new QuizModel(category, 	"The faster the vehicle in front of you is travelling, the", new String[]{	"Closer you must get before starting to overtake.",	"Less time you need to overtake.",	"More distance and time you need to overtake."}, 2));
            list.add(new QuizModel(category, 	"If you are not sure you have enough distance to overtake a vehicle ahead, you should", new String[]{	"Sound your horn to signal the driver ahead to slow down.",	"Put the vehicle in a lower gear and speed up.",	"Wait for a better opportunity with more distance to overtake."}, 2));
            list.add(new QuizModel(category, 	"When being overtaken by another vehicle what should you do to help?", new String[]{	"Brake quickly to let the other vehicle overtake.",	"Keep left and allow plenty of room to let the other vehicle back in.",	"Move to the left and stop."}, 1));
            list.add(new QuizModel(category, 	"Before beginning to overtake another vehicle, you should", new String[]{	"Check to see it is safe, change gear if necessary, and signal your intention before moving out.",	"Signal and slow down so you will have more room to overtake.",	"Sound your horn, move out and overtake."}, 0));
            list.add(new QuizModel(category, 	"The first thing you should do before overtaking is", new String[]{	"Increase your speed.",	"Sound your horn.",	"Make sure it is safe and the way is clear of oncoming traffic."}, 2));
            list.add(new QuizModel(category, 	"Another vehicle is overtaking you on your right. You commit a traffic offence if you", new String[]{	"Speed up while the other vehicle is on your right.",	"Keep the same speed.",	"Slow down while the other vehicle is on your right."}, 0));
            list.add(new QuizModel(category, 	"If you are caught speeding through a road work zone you will", new String[]{	"Be liable for a speeding fine and loss of demerit points.",	"Receive a warning letter in the mail.",	"Not receive any penalty as road works speed limits are only advisory."}, 0));
            list.add(new QuizModel(category, 	"When driving through temporary road work you should", new String[]{	"Receive a warning letter in the mail.",	"Maintain current speed if the road is clear.",	"Sound your horn."}, 1));
            list.add(new QuizModel(category, 	"When entering or leaving a driveway you must", new String[]{	"Stop and give way only to vehicles.",	"Give way to bicycles, vehicles and pedestrians.",	"Blow your horn to warn other road users."}, 1));
            list.add(new QuizModel(category, 	"Will a P1 licence be suspended for any speeding offence?", new String[]{	"Only for 10 km/h or more over the speed limit.",	"No.",	"Yes."}, 2));

            list.add(new QuizModel(category, R.drawable.nd007,	"On a single laned road (as shown), you must always overtake another vehicle on its right except when", new String[]{	"The other vehicle is turning right.",	"You are travelling at more than 80 km/h.",	"The other vehicle is going slower than you."}, 0));
            list.add(new QuizModel(category, R.drawable.nd015,	"You are driving behind a long vehicle (as shown) which has a sign saying DO NOT OVERTAKE TURNING VEHICLE. The long vehicle indicates that it is going to turn left. You", new String[]{	"May move to the left-hand side of the road and pass the long vehicle.",	"Must let the long vehicle turn first.",	"May pass the truck because it cannot turn left from the middle lane."}, 1));
            list.add(new QuizModel(category, R.drawable.nd019,	"How should you overtake a pedal cyclist?", new String[]{	"Sound your horn to warn the cyclist to get off the road.",	"Drive as close as possible to the cyclist so he or she will move over and let you pass.",	"The same as you would another car, with safety."}, 2));
            list.add(new QuizModel(category, R.drawable.nd020,	"If an overtaking vehicle signals that it must move in, in front of you, you should", new String[]{	"Speed up and not let the vehicle back in.",	"Prepare to slow down to allow room.",	"Flash your lights at the overtaking vehicle."}, 1));
            list.add(new QuizModel(category, R.drawable.nd031,	"You are travelling in the left lane and wish to turn right at the intersection. You move to the right lane and a driver behind sounds their horn at you. What have you done wrong?", new String[]{	"Changed lanes unnecessarily.",	"Driven too slowly.",	"Crossed an unbroken lane line."}, 2));
            list.add(new QuizModel(category, R.drawable.nd032,	"What is this driver doing that is negligent and illegal?", new String[]{	"Crossing an unbroken line at a curve.",	"Not signalling to change lanes.",	"Overtaking on the kerb side."}, 0));
            list.add(new QuizModel(category, R.drawable.nd033,	"The speed limit on this road is 90 km/h. You have just overtaken a vehicle in the left lane. What should you do next?", new String[]{	"Move into the left lane.",	"Keep your position in this lane.",	"Accelerate away from the other vehicle and keep driving in this lane."}, 0));
            list.add(new QuizModel(category, R.drawable.nd034,	"The speed limit on this road is 100 km/h. When can you use the right lane?", new String[]{	"When there is no other traffic around.",	"Whenever you want to.",	"Only when overtaking or turning right."}, 2));
            list.add(new QuizModel(category, R.drawable.nd044,	"When you have started to overtake the car, you notice that its right indicator is flashing. You should", new String[]{	"Check your mirror and move back in behind the car.",	"Accelerate quickly to get past.",	"Immediately brake to a stop."}, 0));

        }
        if (category.equals("Pedestrians")) {
            list.add(new QuizModel(category, 	"You must give way to pedestrians on a marked pedestrian crossing", new String[]{	"When they are crossing from your left only.",	"When they are crossing from your right only.",	"If there is any danger of a collision."}, 2));
            list.add(new QuizModel(category, 	"If elderly people or children are on a pedestrian crossing you will probably need to –", new String[]{	"Drive around them so you don't hold up traffic.",	"Sound your horn to hurry them up.",	"Wait extra time to allow them to cross safely."}, 2));
            list.add(new QuizModel(category, 	"Which one of the following statements is correct? Bicycle riders", new String[]{	"May not travel on heavy traffic roads.",	"Must obey the road rules.",	"Must ride against the flow of traffic so they can be seen."}, 1));
            list.add(new QuizModel(category, 	"When driving near children playing or walking near the edge of the road, you should", new String[]{	"Sound your horn to warn them of your presence.",	"Slow down, and be ready to make a safe stop.",	"Continue at the same speed and drive around them."}, 1));
            list.add(new QuizModel(category, 	"Pedestrians who are affected by alcohol, are", new String[]{	"Unlikely to walk near the road and do not require your attention. ",	"One of the most common groups involved in road accidents.",	"Less dangerous than sober pedestrians because they are more careful after drinking."}, 1));
            list.add(new QuizModel(category, 	"When driving near pedestrian crossings, intersections, or school crossings, you should always", new String[]{	"Keep your eyes on the speedo.",	"Move into the left lane.",	"Slow down, watch for pedestrians and be ready to make a safe stop."}, 2));
            list.add(new QuizModel(category, 	"When driving in an area where there are many pedestrians (e.g. a bus stop) it is important to", new String[]{	"Increase your speed to avoid the chance of hitting them.",	"Put your headlights on high beam so they can see you better.",	"Slow down and watch for an indication that they will enter the road."}, 2));
            list.add(new QuizModel(category, 	"When driving past parked vehicles, which of the following is it most important to do –", new String[]{	"Stay as close as possible to the vehicle in front of you.",	"hand lane, if there is one.",	"Drive in the right"}, 2));
            list.add(new QuizModel(category, 	"When driving in wet weather, you should", new String[]{	"Stop and help aged pedestrians across the road.",	"Drive in the middle of the road to avoid splashing pedestrians on the footpath.",	"Watch out for pedestrians, who may hurry and take risks."}, 2));
            list.add(new QuizModel(category, 	"At a pedestrian crossing with traffic lights, when the lights change to red you should", new String[]{	"Slow down and give way to pedestrians.",	"Stop, wait for pedestrians to cross and for the green light to come on.",	"Stop and continue after the pedestrians have crossed."}, 1));
            list.add(new QuizModel(category, 	"You must give way to pedestrians if there is a risk of hitting them. When driving in poor light, you should", new String[]{	"Look more carefully for pedestrians because they are hard to see.",	"Keep your headlights on high beam all the time.",	"Always drive in the right hand lane so you can be away from pedestrians."}, 0));

            list.add(new QuizModel(category, R.drawable.pd002,	"When approaching a marked pedestrian crossing and no pedestrians are in sight, you should", new String[]{	"Come to a complete stop before the crossing.",	"Slow down and be ready to make a safe stop.",	"Go faster, in case a pedestrian steps onto the crossing."}, 1));
            list.add(new QuizModel(category, R.drawable.pd004,	"Which sign painted on the road tells you there is a pedestrian crossing ahead?", new String[]{	"C",	"A",	"B"}, 2));
            list.add(new QuizModel(category, R.drawable.pd005,	"A vehicle ahead of you has stopped at a pedestrian crossing. You", new String[]{	"May overtake the vehicle provided no cars are coming the other way.",	"May overtake the vehicle if there are no pedestrians on the crossing.",	"Must not overtake the stopped vehicle."}, 2));
            list.add(new QuizModel(category, R.drawable.pd006,	"If you see a School Crossing Supervisor holding a sign like this, you must wait until the children", new String[]{	"Are off the crossing and the hand held sign is taken away.",	"Reach the right-hand side of the crossing.",	"Are out of sight."}, 0));
            list.add(new QuizModel(category, R.drawable.pd015,	"At a pedestrian crossing with traffic lights, when the amber light starts 'flashing' after the red stop signal, it means", new String[]{	"The green light is due. Do not proceed until the green light appears.",	"The traffic lights are out of order and pedestrians must not use the crossing.",	"You may carefully drive through the crossing, if there is no risk of colliding with pedestrians."}, 2));
            list.add(new QuizModel(category, R.drawable.pd016,	"Which statement is true?", new String[]{	"Pedestrians have no special rights on the roads.",	"You must give way to pedestrians if there is any danger of hitting them.",	"You must give way to pedestrians only at marked crossings."}, 1));
            list.add(new QuizModel(category, R.drawable.pd017,	"You drive towards these people on the road. What should you do?", new String[]{	"Slow down until they are half way through the crossing and drive on.",	"Continue at the same speed and sound the horn.",	"Stop and give way if there is any danger of hitting them."}, 2));
            list.add(new QuizModel(category, R.drawable.pd018,	"You see these zig-zag markings on the road in front of you. What do they mean?", new String[]{	"Take care and look out for pedestrians at a crossing.",	"Look out for animals on the side of the road.",	"Be careful because the road ahead is slippery."}, 0));
            list.add(new QuizModel(category, R.drawable.pd019,	"These markings on the road indicate", new String[]{	"Places where you can park.",	"Places where pedestrians have special rights.",	"Places where special speed limits apply."}, 1));
            list.add(new QuizModel(category, R.drawable.pd021,	"You approach a person crossing the road. You should", new String[]{	"Maintain your speed and swerve around the person.",	"Slow down and sound your horn to hurry up the person.",	"Slow down or stop to avoid hitting the person."}, 2));
            list.add(new QuizModel(category, R.drawable.pd022,	"You approach a crossing and see the scene in the picture. You should", new String[]{	"Slow down and drive through giving way to the children.",	"Slow down and stop until the supervisor takes down the sign.",	"Stop and wait for the children until your lane is clear."}, 1));
            list.add(new QuizModel(category, R.drawable.pd024,	"This person is standing on a pedestrian refuge. If he steps out onto your lane you should", new String[]{	"Maintain your speed so you do not hold up the traffic.",	"Slow down and sound the horn to warn the person to move back.",	"Give way to the person if there is any danger of colliding."}, 2));
            list.add(new QuizModel(category, R.drawable.pd025,	"Which of the following statements is correct?", new String[]{	"You do not have to give way to adults crossing at children's crossings.",	"Pedestrians must cross the road only at marked crossings and intersections.",	"You must give way to pedestrians if there is a danger of a collision."}, 2));
            list.add(new QuizModel(category, R.drawable.pd026,	"When you see children on or near the road", new String[]{	"You should slow down and be more careful because they may move suddenly.",	"You should reduce your speed by 5 km/h.",	"You should ignore them and pay attention to the rear vision mirror."}, 0));
            list.add(new QuizModel(category, R.drawable.pd027,	"When you see older people on or near the road, you should", new String[]{	"Slow down and take extra care because they may not see you until you are very close.",	"Drive around them to keep the traffic moving.",	"Sound your horn and keep going at the same speed so you do not hold up the traffic."}, 0));
            list.add(new QuizModel(category, R.drawable.pd030,	"You drive up to a Light Rail vehicle that has just stopped at a tram stop. What is the most important thing you should do?", new String[]{	"Keep a look out for traffic coming in the opposite direction.",	"Take extra care, slow down and give way to the pedestrians.",	"Slow down, but keep moving so you do not delay other drivers."}, 1));

        }
        if (category.equals("Rider Safety")) {
            list.add(new QuizModel(category, 	"Properly adjusted mirrors will allow you to see", new String[]{	"About half of the lane behind you and as much as possible of the lane beside you.",	"Into the lane beside you.",	"Only behind you."}, 0));
            list.add(new QuizModel(category, 	"Good control of your motorcycle may be achieved by", new String[]{	"Gripping the handlebars as tightly as possible.",	"Adopting a correct relaxed riding position.",	"Sitting as far back on the seat as possible to give the rear tyre more grip."}, 1));
            list.add(new QuizModel(category, 	"A good riding position should feel comfortable and allow you to", new String[]{	"Have fast effective use of the controls without affecting the balance.",	"Ride faster in all traffic conditions.",	"Relax more and enjoy your riding."}, 0));
            list.add(new QuizModel(category, 	"Sitting too far back on the seat of your motorcycle will", new String[]{	"Affect weight distribution making steering very light.",	"Give your rear tyre more grip for braking at speed. ",	"Not affect the motorcycle noticeably."}, 0));
            list.add(new QuizModel(category, 	"Sticking your knees out when cornering your motorcycle on a road", new String[]{	"Is a tried and proven method of cornering.",	"Is not a good or efficient style of riding on a road.",	"Will make you corner faster."}, 1));
            list.add(new QuizModel(category, 	"When approaching a turn on your motorcycle you should", new String[]{	"Slow down before the turn and increase your speed gradually as you come out of the turn.",	"Leave your braking until you are in the turn so you do not lose too much speed.",	"Cover your brakes in case you need them while in the turn."}, 0));
            list.add(new QuizModel(category, 	"Best braking is achieved when a motorcycle is", new String[]{	"Carrying a load and travelling at the sign posted speed limit.",	"Leaned over whilst cornering.",	"Upright and travelling in a straight line."}, 2));
            list.add(new QuizModel(category, 	"To stop a motorcycle well, you should always use", new String[]{	"Only the front brake at high speed.",	"Both brakes together.",	"Only the rear brake at high speed."}, 1));
            list.add(new QuizModel(category, 	"Is it best to change gears before, during or after a turn?", new String[]{	"After. ",	"Before.",	"During."}, 1));
            list.add(new QuizModel(category, 	"Riders may make themselves more noticeable to car drivers by", new String[]{	"Riding closely behind cars.",	"Wearing bright, fluorescent or contrasting coloured clothing.",	"Riding to the side of cars at all times."}, 1));
            list.add(new QuizModel(category, 	"To make yourself more visible to oncoming vehicles during the day", new String[]{	"Ride with your headlight off.",	"Ride with your headlight on low beam.",	"Flash your brake light every now and then."}, 1));
            list.add(new QuizModel(category, 	"When an oncoming vehicle seems ready to turn across your path as you approach it, you should", new String[]{	"Check your mirrors, slow down and, if possible, move to your left away from the vehicle.",	"Keep your speed and lane position constant so the driver knows you want to go straight ahead.",	"Increase your speed so you can get clear of the car before it turns."}, 0));
            list.add(new QuizModel(category, 	"'Head checks' are what drivers and riders do to", new String[]{	"See what is to the front side of them.",	"See what is behind them.",	"See what is in their 'blind spots'."}, 2));
            list.add(new QuizModel(category, 	"To allow yourself time to stop when following another vehicle in dry weather you should stay at least", new String[]{	"Three seconds behind the vehicle in front.",	"Two seconds behind the vehicle in front.",	"One car length behind the vehicle in front."}, 0));
            list.add(new QuizModel(category, 	"When riding past parked cars motorcycle riders should", new String[]{	"Flash the bike's headlight as a warning to anyone in or near the cars.",	"Create sufficient space from the cars to avoid opening doors or people stepping from between the cars.",	"Be ready to sound their horn if someone should open a door or step from between the cars."}, 1));
            list.add(new QuizModel(category, 	"When riding on a wet or slippery road riders should", new String[]{	"Ride at a normal constant speed as sign posted for the area.",	"Reduce speed so that it requires less time if they need to stop.",	"Ride around with their hands on the brake lever and foot on the brake pedal in case they have to stop in a hurry."}, 1));
            list.add(new QuizModel(category, 	"When a road is wet the most slippery part is likely to be", new String[]{	"The left side of your lane.",	"The centre of your lane.",	"The right side of your lane."}, 1));
            list.add(new QuizModel(category, 	"When cornering on a wet or slippery surface riders should", new String[]{	"Lean as much as normal for the corner only be smoother on the throttle.",	"Sit towards the back of the motorcycle to give more grip to the rear wheel.",	"Reduce the lean angle of the motorcycle so the tyres will grip better."}, 2));
            list.add(new QuizModel(category, 	"When riding a motorcycle at night you should", new String[]{	"Ride at all times with your headlight on high beam to give you better vision.",	"Reduce speed even on roads you know well as you cannot see very far ahead at night.",	"Ride as you normally would in daytime."}, 1));
            list.add(new QuizModel(category, 	"An important part of observation is", new String[]{	"Constantly performing head checks.",	"Scanning.",	"Keeping your chin up and look straight at all times."}, 1));
            list.add(new QuizModel(category, 	"The amount of time it take to react and respond to a sudden change in traffic is generally", new String[]{	"Three seconds.",	"Two seconds.",	"Less than a second."}, 0));
            list.add(new QuizModel(category, 	"You should check your mirrors", new String[]{	"Before every ride.",	"Before you accelerate or brake so that you do not force people to change their speed.",	"Every few seconds so that you always know what is behind you."}, 2));
            list.add(new QuizModel(category, 	"When riding towards the crest of a hill, it is best to", new String[]{	"Change to a lower gear and apply more throttle.",	"Maintain a constant speed so that you do not confuse drivers behind you.",	"Slow down and buffer from possible oncoming traffic."}, 2));
            list.add(new QuizModel(category, 	"Recommended additional protection for riders includes", new String[]{	"Wearing kidney belts and back protectors.",	"Wearing water-proof clothing.",	"Wearing sunglasses under your visor."}, 0));
            list.add(new QuizModel(category, 	"In addition to wearing a motorcycle helmet you should", new String[]{	"Wear a hair-net to help your helmet last longer.",	"Make sure that you also wear sunglasses for additional protection.",	"Ensure that you always wear motorcycle specific clothing."}, 2));
            list.add(new QuizModel(category, 	"When riding on a single lane road, a motorcycle rider ", new String[]{	"Can legally use any part of the lane.",	"Must remain in the left of the lane at all times.",	"Must remain in the middle of the lane at all times."}, 0));
            list.add(new QuizModel(category, 	"When turning you should look", new String[]{	"In the direction you wish to go.",	"Down, so you can see the road immediately in front of you.",	"At traffic coming from behind."}, 0));
            list.add(new QuizModel(category, 	"When you see an oncoming vehicle you should", new String[]{	"Swerve to avoid it, while braking.",	"Always slow down.",	"Create a buffer between you and the other vehicle."}, 2));
            list.add(new QuizModel(category, 	"When taking a left curve you should", new String[]{	"Plan to finish in the left part of your lane.",	"Brake as late as possible to maintain your speed and balance.",	"Lean your motorcycle and apply the brakes throughout the corner."}, 0));

            list.add(new QuizModel(category, R.drawable.rs001,	"You are approaching the intersection shown, and an on", new String[]{	"Proceed straight ahead at normal speed.",	"Move towards the left of your lane and slow down.",	"Stop, and let the car turn right."}, 1));
            list.add(new QuizModel(category, R.drawable.rs003,	"In this diagram which light is most likely to make the motorcycle more noticeable to the car driver?", new String[]{	"The tail-light.",	"The headlight on high beam.",	"The right turn indicator."}, 2));
            list.add(new QuizModel(category, R.drawable.rs004,	"You are riding the motorcycle shown, what would you need to do to be able to see the car?", new String[]{	"Look in the mirror.",	"Turn your head.",	"Take off your helmet."}, 1));
            list.add(new QuizModel(category, R.drawable.rs005,	"In the diagram shown you are being followed very closely by another vehicle, you should", new String[]{	"Attempt to get the other vehicle to drop back by giving a hand signal.",	"Create more space in front of you by slowing down, until it is safe for the other vehicle to pass.",	"Brake hard to force the other vehicle to drop back."}, 1));

        }
        if (category.equals("Speed Limits")) {
            list.add(new QuizModel(category, 	"Driving faster than the maximum speed limit is", new String[]{	"Permitted only when passing another vehicle.",	"Never legally permitted.",	"Only permitted when other vehicles are going faster than the speed limit."}, 1));
            list.add(new QuizModel(category, 	"A Shared Traffic Zone, where pedestrians and other road users can share the road safely has a speed limit of", new String[]{	"10 Km/h.",	"20 Km/h.",	"50 Km/h."}, 0));
            list.add(new QuizModel(category, 	"What could be the penalties for driving over the speed limit", new String[]{	"A letter of warning and a small fine.",	"Fines only.",	"Fines, demerit points and possibly loss of licence."}, 2));
            list.add(new QuizModel(category, 	"Where there are no speed limit signs, the speed limit is 100 km/h, unless", new String[]{	"There are street lights along the road.",	"The road you are driving on is gravel.",	"There's an emergency, which mean speed limits don't apply."}, 0));
            list.add(new QuizModel(category, 	"If you are driving along the highway and come across road works with a reduced speed zone, you must", new String[]{	"Drive at the same speed as other vehicles.",	"Drive through the road works zone as fast as you can to get past it.",	"Slow down to the new speed limit."}, 2));

            list.add(new QuizModel(category, R.drawable.sl002,	"On a freeway with a maximum speed limit of 110 km/h, a learner driver or rider must not drive faster than", new String[]{	"100 km/h.",	"80 km/h.",	"110 km/h."}, 1));
            list.add(new QuizModel(category, R.drawable.sl030,	"When you see this sign you must", new String[]{	"Drive at a speed less than 40 km/h if you are not a resident of the local zone.",	"Only enter the street if you live in the local zone.",	"Not exceed 40 km/h and keep a special lookout for bicycle riders, pedestrians and children."}, 2));
            list.add(new QuizModel(category, R.drawable.sl031,	"This sign means you must", new String[]{	"Share this road with other people and vehicles and not exceed 10 km/h.",	"Drive at 10 km/h if there are pedestrians around.",	"Reduce your speed to what you think is safe but never below 10 km/h."}, 0));

        }
        if (category.equals("Lights and Lanes")) {
            list.add(new QuizModel(category, 	"How should you merge with traffic when entering a freeway?", new String[]{	"Watch for a gap and merge with the traffic at the speed it is travelling.",	"Speed up and force your way into the traffic.",	"Stop, then enter the traffic quickly."}, 0));
            list.add(new QuizModel(category, 	"Double unbroken dividing lines are marked on a roadway. You may", new String[]{	"Cross them to turn into a driveway or property, if it is safe to do so.",	"Cross them to overtake a car ahead if it is safe to do so.",	"Cross them to make a U turn."}, 0));
            list.add(new QuizModel(category, 	"You must use your indicator lights when ", new String[]{	"Double parking.",	"Changing lanes or turning left or right.",	"Approaching a curve."}, 1));
            list.add(new QuizModel(category, 	"If you hear the siren of an emergency vehicle, you must", new String[]{	"Take whatever action is necessary (with safety) to make way for the emergency vehicle.",	"Flash your headlights to warn other drivers.",	"Increase your speed to avoid the vehicle."}, 0));
            list.add(new QuizModel(category, 	"When driving on a multi-lane road with a speed limit of more than 80 km/h, which lane should you choose?", new String[]{	"The left lane unless overtaking.",	"The right lane to avoid slow moving vehicles.",	"Either left or right lane."}, 0));
            list.add(new QuizModel(category, 	"Signalling is ", new String[]{	"Always required before turning or lane changing.",	"Not required when turning at T-intersections.",	"Not required when turning at traffic lights with a green arrow."}, 0));
            list.add(new QuizModel(category, 	"How should you merge with traffic when entering a motorway?", new String[]{	"Slow down and force your way into the traffic.",	"Watch for a gap and increase your speed to safely merge with the traffic.",	"Stop, then enter the traffic quickly."}, 1));
            list.add(new QuizModel(category,	"Are you permitted to make a U-Turn at traffic lights?", new String[]{	"Yes, at all times.",	"No, unless there is a U-TURN PERMITTED sign at the intersection.",	"Yes, if there is no danger of colliding with another vehicle."}, 1));

            list.add(new QuizModel(category, R.drawable.ld002,	"Which movements shown in the diagram can legally be made by the driver of the purple car?", new String[]{	"O and P only.",	"P only.",	"O,PandQ."}, 0));
            list.add(new QuizModel(category, R.drawable.ld003,	"Which movements shown in the diagram can legally be made by the driver of the purple car?", new String[]{	"P only.",	"OandPonly.",	"O, P and Q."}, 2));
            list.add(new QuizModel(category, R.drawable.ld004,	"Which movements shown in the diagram can legally be made by the driver of the purple car?", new String[]{	"P only.",	"O and P only.",	"O,PandQ."}, 1));
            list.add(new QuizModel(category, R.drawable.ld007,	"A section of road is marked with double unbroken dividing lines as in the diagram. When is a vehicle allowed to cross these lines?", new String[]{	"When there is no traffic coming the other way.",	"To overtake a slow vehicle ahead.",	"To enter or leave a street or driveway."}, 2));
            list.add(new QuizModel(category, R.drawable.ld009,	"When driving in traffic lanes (as shown in the diagram), you may change your lane", new String[]{	"Only when it is safe to do so.",	"Without looking, provided you use your indicator",	"Provided you sound your horn to warn other drivers."}, 0));
            list.add(new QuizModel(category, R.drawable.ld010,	"When two lanes merge into one (as shown in the diagram), who should give way?", new String[]{	"hand lane because it is overtaking.",	"The vehicle in the right",	"The faster vehicle."}, 2));
            list.add(new QuizModel(category, R.drawable.ld011,	"Looking at the diagram, which vehicle must give way?", new String[]{	"Either vehicle, there is no rule on giving way when merging.",	"Vehicle A.",	"Vehicle B."}, 2));
            list.add(new QuizModel(category, R.drawable.ld017,	"When the road is marked this way are you permitted to cross the lines and overtake?", new String[]{	"No.",	"Yes.",	"Yes, only if the way ahead is clear."}, 0));
            list.add(new QuizModel(category, R.drawable.ld033,	"What does this sign mean?", new String[]{	"Slow down and prepare to stop for a train.",	"You are approaching a lane that is only for buses.",	"There is a lane just for light rail vehicles."}, 2));

            list.add(new QuizModel(category, R.drawable.tl001,	"You are facing traffic lights (as shown). What do they mean?", new String[]{	"You may proceed only in the direction of the green arrow.",	"You may proceed only in the direction of the green arrow when the red light has changed to green.",	"You must give way to oncoming traffic."}, 0));
            list.add(new QuizModel(category, R.drawable.tl002,	"At traffic lights what is meant when a red light appears?", new String[]{	"Stop, make sure there is no traffic, then drive straight ahead.",	"Stop, wait behind the stop line until the lights change to yellow.",	"Stop, wait behind the stop line until the lights change to green."}, 2));
            list.add(new QuizModel(category, R.drawable.tl003,	"What should you do when approaching traffic lights which change from green to yellow?", new String[]{	"Stop, only if a red light camera is in use.",	"Speed up to clear the intersection before the lights change to red.",	"Stop at the stop line unless you are so close that sudden or sharp braking might cause an accident."}, 2));
            list.add(new QuizModel(category, R.drawable.tl004,	"What may you do at an intersection with traffic lights at which this sign is displayed?", new String[]{	"You may turn left only if a green arrow is shown.",	"You should slow down and check if anyone is coming before turning left.",	"If the lights are red you must first stop, then you may turn left if it is safe to do so."}, 2));
            list.add(new QuizModel(category, R.drawable.tl006,	"These lights mean that you", new String[]{	"Can turn left, but not go straight ahead.",	"Can turn left or go straight ahead.",	"Can turn left only if a sign 'TURN LEFT AT ANY TIME WITH CARE' is displayed."}, 0));
            list.add(new QuizModel(category, R.drawable.tl007,	"This light means, you", new String[]{	"Can go straight ahead, or turn left or turn right, if it is safe to do so.",	"Must stop and wait for the red light before proceeding.",	"Can make a U turn provided it is safe to do so."}, 0));
            list.add(new QuizModel(category, R.drawable.tl008,	"It is 3 o'clock in the morning. You cannot see any other traffic. You want to turn right. You may", new String[]{	"Not turn right while the arrow is red.",	"Turn right when you have waited one minute.",	"Turnrightifitissafetodoso."}, 0));
            list.add(new QuizModel(category, R.drawable.tl010,	"As you approach an intersection with traffic lights, the yellow light turns to red. You must", new String[]{	"Speed up to avoid traffic from the left and right.",	"Stop and wait for the green light.",	"Sound your horn and proceed through the red light."}, 1));
            list.add(new QuizModel(category, R.drawable.tl011,	"You approach an intersection showing a red light and the sign shown. You wish to turn left. You must", new String[]{	"Slow down and turn left or right if it is safe.",	"Stop and wait for a green light.",	"Stop and turn left only if it is safe."}, 2));
            list.add(new QuizModel(category, R.drawable.tl013,	"You are waiting at an intersection and the lights are red. The traffic lights change to green. You should", new String[]{	"Wait until the traffic behind you makes you move.",	"Cross the intersection as quickly as possible.",	"Check both sides of the intersection and then proceed."}, 2));
            list.add(new QuizModel(category, R.drawable.tl014,	"You want to turn right at an intersection and see this traffic light. You should", new String[]{	"Enter the intersection and wait for the green arrow.",	"Move forward slowly.",	"Stay behind the stop line until the green arrow shows."}, 2));

            list.add(new QuizModel(category, R.drawable.tl015,	"You wish to turn left at this intersection. The traffic lights are red and you see this sign. You should", new String[]{	"Stop until the light turns green.",	"Stop, then if you see it is safe turn left.",	"Stop then go straight ahead."}, 1));
            list.add(new QuizModel(category, R.drawable.tl016,	"You wish to turn left at this intersection and the traffic lights are green. What should you do?", new String[]{	"Move forward slowly, make the left turn and wait behind car A.",	"Enter the intersection and sound the horn. ",	"Wait behind the stop line until there is room for you to enter the new road."}, 2));
            list.add(new QuizModel(category, R.drawable.tl017,	"As you approach a set of traffic lights at an intersection, they change from green to yellow (amber). You must", new String[]{	"Drive through the intersection without accelerating.",	"Stop before the lights, unless you are so close that sudden braking might cause an accident.",	"Accelerate to clear the intersection before the lights change to red."}, 1));
            list.add(new QuizModel(category, R.drawable.tl018,	"Temporary traffic lights at road works", new String[]{	"Are installed to warn motorists of construction works.",	"Apply to road works vehicles only.",	"Must be obeyed."}, 2));
            list.add(new QuizModel(category, R.drawable.tl019,	"Where do you stop at temporary traffic lights? ", new String[]{	"At the ‘Stop here on red signal’ sign.",	"Where the lane ends.",	"After the traffic lights, but before the construction zone."}, 0));

        }
        if (category.equals("Alcohol and Drugs")) {
            list.add(new QuizModel(category, 	"To reduce the effect of alcohol before driving or riding you should", new String[]{	"Drink black coffee.",	"Wait. The time depends on how much you have drunk.",	"Have a glass of water."}, 1));
            list.add(new QuizModel(category, 	"Before driving a motor vehicle or riding a motor cycle it is safest", new String[]{	"Drink 1 nip of spirits (30 ml or 1 oz).",	"Not to drink any alcohol.",	"Drink 1 middy (285 ml) of light (low alcohol) beer."}, 1));
            list.add(new QuizModel(category, 	"Is it an offence to refuse to take a POLICE breath test?", new String[]{	"Yes, always.",	"No, if you say you haven't been drinking alcohol.",	"No, if you are a learner driver."}, 0));
            list.add(new QuizModel(category, 	"If you take medicine and then drink alcohol", new String[]{	"Your ability to react to emergencies will improve.",	"The alcohol will have less effect than if taken alone.",	"It can have a particularly bad effect on your driving ability."}, 2));
            list.add(new QuizModel(category, 	"Having 1 or 2 alcoholic drinks before driving", new String[]{	"Will affect your reactions and judgement.",	"Improves your driving ability.",	"Has no effect on your driving ability."}, 0));
            list.add(new QuizModel(category, 	"Even if you feel unaffected after drinking alcohol, you should", new String[]{	"Drive, but avoid using freeways.",	"Be aware that your abilities are decreased.",	"Spend more time than usual looking in the mirrors."}, 1));
            list.add(new QuizModel(category, 	"Alcohol is a depressant. This means", new String[]{	"It slows down how quickly your brain works.",	"It speeds your brain up so you can work better.",	"It makes you calm down and think more clearly."}, 0));
            list.add(new QuizModel(category, 	"After drinking alcohol you could", new String[]{	"Misjudge speed (your own and others).",	"Be able to drive the same as you normally can.",	"Be able to pay close attention to details in the traffic."}, 0));
            list.add(new QuizModel(category, 	"Which of the following statements relating to motorcyclists and bicycle riders is correct?", new String[]{	"Alcohol improves their concentration.",	"Alcohol affects their sense of balance.",	"Alcohol improves their reflexes and judgement."}, 1));
            list.add(new QuizModel(category, 	"Consuming even small amounts of alcohol before riding may", new String[]{	"Help clear your mind by relaxing you.",	"Affect your ability to control your motorcycle and make riding dangerous.",	"Have no effect whatsoever on you."}, 1));
            list.add(new QuizModel(category, 	"What is the safest way to stay under the legal alcohol limit?", new String[]{	"Buying a breathlayser (alcohol measuring instrument).",	"Not drinking any alcohol.",	"Exercising and drinking black coffee."}, 1));
            list.add(new QuizModel(category, 	"If you are taking any sort of medicine, you should", new String[]{	"Find out from your doctor or chemist whether the medicine or drug will affect your driving and act accordingly.",	"Only drive during the day after taking the medicine or drug.",	"Only drive a motor car not a heavy vehicle."}, 0));
            list.add(new QuizModel(category, 	"Before taking any drugs and then driving it is most important to", new String[]{	"Plan to have some other person with you.",	"Know what the effects of the drug are.",	"Have some food in your stomach."}, 1));
            list.add(new QuizModel(category, 	"If you have used illegal drugs you", new String[]{	"Must not drive.",	"May drive only in light traffic.",	"Should drink coffee before driving."}, 0));
            list.add(new QuizModel(category, 	"To ensure prescription drugs will not affect your ability to ride a motorcycle you should", new String[]{	"Not ride at all while taking any medication.",	"Tell your doctor you ride a motorcycle, check with your pharmacist and read the label on the drugs.",	"Not take the medication if you want to ride."}, 1));

        }
        if (category.equals("Traffic Signs 1")) {
            list.add(new QuizModel(category, R.drawable.s001,	"When you see this sign you should", new String[]{	"Drive with caution.",	"Not drive beyond the sign.",	"Not pass another vehicle."}, 1));
            list.add(new QuizModel(category, R.drawable.s002,	"This sign means you should", new String[]{	"Pass to the left of the sign.",	"Turn left at next street.",	"Drive carefully, roundabout ahead."}, 0));
            list.add(new QuizModel(category, R.drawable.s003,	"What does this sign mean?", new String[]{	"All right lane traffic must turn right at the next intersection.",	"Right lane traffic may turn right or go straight ahead at the next intersection.",	"One way traffic ahead."}, 0));
            list.add(new QuizModel(category, R.drawable.s004,	"What does this sign mean?", new String[]{	"No turns permitted.",	"Traffic travels in each direction.",	"Double lane bridge ahead."}, 1));
            list.add(new QuizModel(category, R.drawable.s006,	"What does this sign mean?", new String[]{	"You may turn to the right.",	"You must not turn to the right.",	"You must give way to traffic on your right."}, 1));
            list.add(new QuizModel(category, R.drawable.s007,	"What does this sign mean?", new String[]{	"You must not turn to the right.",	"You must not turn to the left or the right.",	"You must not turn to the left."}, 2));
            list.add(new QuizModel(category, R.drawable.s008,	"What does this sign mean?", new String[]{	"Follow the arrow unless you are turning right.",	"All traffic must travel in the direction of the arrow.",	"Road curves to the left ahead."}, 1));
            list.add(new QuizModel(category, R.drawable.s009,	"What does this sign mean?", new String[]{	"You may travel only in the direction in which the arrow is pointing.",	"No left turn.",	"One lane bridge ahead, slow down."}, 0));
            list.add(new QuizModel(category, R.drawable.s013,	"What does this sign mean?", new String[]{	"You are not to exceed 60 km/h.",	"You can go faster than 60 km/h.",	"You are on Highway 60."}, 0));
            list.add(new QuizModel(category, R.drawable.s014,	"What does this sign mean?", new String[]{	"You must not drive faster than 100 km/h.",	"You must drive faster than 100 km/h.",	"The sign applies to truck drivers only, cars can travel at any speed."}, 0));
            list.add(new QuizModel(category, R.drawable.s016,	"What does this sign mean?", new String[]{	"Nature reserve 30 km ahead.",	"Zoo 30 km ahead.",	"Drive carefully, and watch out for kangaroos entering the road for the next 30 km."}, 2));

            list.add(new QuizModel(category, R.drawable.s017,	"What does this sign mean?", new String[]{	"Tollway ahead, be prepared to stop and pay toll.",	"No through road ahead, slow down.",	"intersection ahead. If you are on the terminating road, you must give way to all vehicles approaching from your right or left."}, 2));
            list.add(new QuizModel(category, R.drawable.s018,	"When you see this sign you", new String[]{	"May stop at any time to pick up or drop off passengers.",	"Must not stop here at any time.",	"Must not stop your vehicle at the kerb during the times shown."}, 2));
            list.add(new QuizModel(category, R.drawable.s019,	"You are most likely to find this sign", new String[]{	"On the approach to a bridge which has room for only two vehicles, slow down and proceed with caution.",	"When a bridge is not safe to drive on.",	"If there is a footbridge for pedestrians ahead."}, 0));
            list.add(new QuizModel(category, R.drawable.s020,	"What does this sign mean?", new String[]{	"sharp turns in the road ahead.",	"Road may be slippery when wet, slow down and drive carefully.",	"Road under repair, drive carefully."}, 1));
            list.add(new QuizModel(category, R.drawable.s021,	"You are most likely to find this sign", new String[]{	"If there is a steep hill ahead.",	"As you approach a winding road, slow down and drive with caution.",	"If an unsealed road is ahead."}, 1));
            list.add(new QuizModel(category, R.drawable.s022,	"What does this sign mean?", new String[]{	"A sharp depression in the road is ahead, be prepared, slow down.",	"Do not drive with your lights on high beam.",	"Police station ahead."}, 0));
            list.add(new QuizModel(category, R.drawable.s024,	"What does this sign mean?", new String[]{	"No right turn allowed.",	"Turn around and go back, you are going the wrong way.",	"sharp bend to the right ahead, slow down and drive carefully."}, 2));
            list.add(new QuizModel(category, R.drawable.s025,	"You are most likely to find this sign, where", new String[]{	"Children may be crossing the road ahead, slow down and be prepared to make a safe stop.",	"There is an athletic field ahead.",	"Pedestrians are not allowed."}, 0));
            list.add(new QuizModel(category, R.drawable.s026,	"What does this sign mean?", new String[]{	"Hospital ahead, drive carefully.",	"Crossroads ahead, reduce your speed and watch out for other traffic and pedestrians.",	"Cemetery ahead."}, 1));
            list.add(new QuizModel(category, R.drawable.s027,	"If the red lights on this sign are flashing what are you required to do?", new String[]{	"slow down and drive carefully over the crossing if you cannot see a train approaching.",	"stop until red lights stop flashing then drive on if it is safe to do so.",	"stop until train has passed then proceed immediately."}, 1));
            list.add(new QuizModel(category, R.drawable.s028,	"You should expect this sign, if", new String[]{	"You are approaching an intersection with traffic lights, be prepared to stop.",	"You are approaching a school or playground.",	"A give way sign at an intersection is ahead, slow down and be prepared to stop."}, 2));

            list.add(new QuizModel(category, R.drawable.s030,	"What does this sign mean?", new String[]{	"Trucks must use low gear.",	"slow down and beware of trucks entering from the side.",	"Heavy vehicle checking station ahead."}, 1));
            list.add(new QuizModel(category, R.drawable.s031,	"What does this sign mean?", new String[]{	"stop and help aged pedestrians across the road.",	"slow down and look out for pedestrians crossing the road ahead.",	"Hospital ahead, slow down and proceed with caution."}, 1));
            list.add(new QuizModel(category, R.drawable.s032,	"What does this sign mean?", new String[]{	"Pedestrian crossing ahead, slow down and be prepared to stop.",	"Overhead footbridge for pedestrians ahead.",	"Joggers ahead, drive carefully."}, 0));

        }
        if (category.equals("Traffic Signs 2")) {
            list.add(new QuizModel(category, R.drawable.s033,	"You should expect this sign", new String[]{	"If a one way street is ahead.",	"When a divided road ends and two way traffic is ahead.",	"If a one lane bridge is ahead."}, 1));
            list.add(new QuizModel(category, R.drawable.s035,	"What does this sign mean?", new String[]{	"Workers ahead, slow down and be prepared to stop.",	"Children's playground ahead, slow down and be prepared to stop.",	"Do not litter."}, 0));
            list.add(new QuizModel(category, R.drawable.s036,	"What does this sign mean?", new String[]{	"Watch out for bicycle riders along the roadway or when turning.",	"Bicycle riders not allowed on the roadway.",	"You are approaching a children's playground, slow down."}, 0));
            list.add(new QuizModel(category, R.drawable.s038,	"What does this sign mean?", new String[]{	"stop, red light camera in operation.",	"If traffic lights are out of order or the amber light is flashing, you must stop and give way to traffic as if you are at an intersection with stop signs.",	"stop at all times and give way to all traffic."}, 1));
            list.add(new QuizModel(category, R.drawable.s039,	"What does this sign mean?", new String[]{	"One way traffic ahead.",	"You are approaching a roundabout, prepare to give way.",	"stop sign ahead, slow down and prepare to stop."}, 2));
            list.add(new QuizModel(category, R.drawable.s040,	"What does this sign mean?", new String[]{	"Traffic controller ahead, slow down and be prepared to stop.",	"school children crossing the road ahead, prepare to stop. ",	"Traffic lights out of order, Police on duty ahead."}, 0));
            list.add(new QuizModel(category, R.drawable.s041,	"What does this sign mean?", new String[]{	"Road ahead slippery when wet, drive carefully.",	"grade in the road ahead, slow down.",	"Road under repair, slow down."}, 1));
            list.add(new QuizModel(category, R.drawable.s042,	"What does this sign mean?", new String[]{	"Freeway conditions are ahead, maximum speed is 100 km/h",	"A two lane bridge is ahead, slow down and drive carefully.",	"A divided road is ahead, prepare for a change in traffic conditions."}, 2));

            list.add(new QuizModel(category, R.drawable.s043,	"What does this sign mean?", new String[]{	"Intersection ahead with traffic lights, prepare to stop.",	"Railway level crossing with flashing signals ahead, slow down, drive carefully, and be prepared to stop.",	"Red light camera in use at traffic lights ahead."}, 1));
            list.add(new QuizModel(category, R.drawable.s045,	"What does this sign mean?", new String[]{	"Merging traffic, give way to your right.",	"Form one lane of traffic.",	"Road narrows ahead, slow down and prepare for a change in traffic conditions."}, 2));
            list.add(new QuizModel(category, R.drawable.s046,	"What does this sign mean?", new String[]{	"Vehicles are not allowed to stop at the kerb except in a medical emergency.",	"Vehicles must not stop at the kerb, except if picking up a passenger.",	"Vehicles must not stop at the kerb, unless picking up goods."}, 0));
            list.add(new QuizModel(category, R.drawable.s048,	"What does this sign mean?", new String[]{	"Vehicles carrying three or more people, and motorcycles may use this lane.",	"Motor cars carrying one passenger may use this lane.",	"This lane is reserved for bicycle riders only."}, 0));
            list.add(new QuizModel(category, R.drawable.s049,	"What does this sign mean?", new String[]{	"Railway level crossing ahead, slow down and look out for trains, be prepared to stop.",	"Cattle or sheep crossing the road ahead, drive slowly.",	"Give way sign ahead, slow down and be prepared to stop."}, 0));
            list.add(new QuizModel(category, R.drawable.s050,	"What does this sign mean?", new String[]{	"Drive carefully and watch out for traffic entering from a side-road intersection ahead.",	"Take care, trucks crossing the road ahead.",	"Take a break, rest area ahead. "}, 0));
            list.add(new QuizModel(category, R.drawable.s051,	"When you see this sign you must", new String[]{	"stop at the stop line and give way to all traffic on your right only.",	"stop at the stop line and give way to all traffic.",	"slow down and be prepared to stop only if there is any danger of a collision with another vehicle or pedestrian."}, 1));
            list.add(new QuizModel(category, R.drawable.s052,	"When you see this sign you must", new String[]{	"stop and give way to all traffic even if the intersection is clear.",	"slow down and be prepared to stop and give way to all traffic if there is any danger of a collision.",	"slow down and be prepared to give way to traffic on your right only, if there is any danger of a collision."}, 1));
            list.add(new QuizModel(category, R.drawable.s053,	"When you see this sign you should", new String[]{	"slow down, then drive slowly over the crossing looking both ways for trains.",	"Come to a complete stop, look both ways for trains and proceed with caution if no trains are approaching.",	"stop, only if a train is at the crossing."}, 1));
            list.add(new QuizModel(category, R.drawable.s056,	"What does this sign mean?", new String[]{	"Next main town 35 km to the right.",	"Winding road ahead for next 35 km.",	"slow down, the maximum safe speed around the next curve in the road is 35km/h."}, 2));
            list.add(new QuizModel(category, R.drawable.s057,	"When you see this sign you should", new String[]{	"slow down and be prepared to stop if the lights start flashing, warning you of an approaching train.",	"Continue at the same speed and not look both ways for approaching trains.",	"stop in the middle of the railway tracks and look both ways for approaching trains."}, 0));

            list.add(new QuizModel(category, R.drawable.s058,	"What does this sign means?", new String[]{	"You must stay in the left lane and must not overtake any vehicles.",	"You must stay in or move to the left lane, unless you are overtaking another vehicle.",	"You can overtake vehicles only on the left side."}, 1));
            list.add(new QuizModel(category, R.drawable.s059,	"What does this sign means?", new String[]{	"slow down and be ready to stop and give way to a train.",	"stop before the railway crossing, wait for 1 minute and proceed if the crossing is clear.",	"Drive quickly over the railway crossing."}, 0));
            list.add(new QuizModel(category, R.drawable.s060,	"What does this sign means?", new String[]{	"stop at all times and give way to all traffic on your right.",	"All traffic must turn back at the roundabout.",	"slow down, be ready to stop and give way to all vehicles already on the roundabout if there is a danger of a collision."}, 2));
            list.add(new QuizModel(category, R.drawable.s061,	"When you see this sign you should", new String[]{	"Watch out, the road ahead may be flooded.",	"Drive carefully, you are reaching the top of the hill and will not be able to see a safe distance in front of you.",	"slow down, there is a dangerous curve ahead."}, 1));
            list.add(new QuizModel(category, R.drawable.s062,	"What does this sign mean?", new String[]{	"There is a hump (sudden slope up and down) in the road ahead, slow down.",	"There is a tunnel ahead, turn on your headlights.",	"The road ahead is closed, go back."}, 0));
            list.add(new QuizModel(category, R.drawable.s063,	"What does this sign tell you?", new String[]{	"You are approaching an animal farm.",	"Animals are crossing the road ahead, stop and wait for directions.",	"There may be animals on or near the road ahead, slow down and be prepared to stop to avoid collision."}, 2));
            list.add(new QuizModel(category, R.drawable.s064,	"What does this sign mean?", new String[]{	"Vehicles may park in this area for up to ten minutes.",	"Motorcyclists may park in this area.",	"Only vehicles carrying a disable person and displaying a mobility parking authority may park in this area."}, 2));

        }
        return list;
    }

    public int getSize(String category) {
        return listQuiz(category).size();
    }
}
